"""API tests for ComplianceRule, ComplianceRuleSet, and ComplianceTestResult.

Uses Nautobot's `APIViewTestCases.APIViewTestCase`, which exercises list/get/create/
update/delete both with and without the relevant object permission -- so each test
case below covers create/read/update/delete plus a permission-denied case for a user
without the right role, without hand-rolling that matrix.
"""

from django.contrib.contenttypes.models import ContentType
from django.urls import reverse
from nautobot.core.testing import APITestCase, APIViewTestCases
from nautobot.dcim.models import Device, DeviceType, Location, LocationType, Manufacturer
from nautobot.extras.models import Role, Status
from rest_framework import status

from nautobot_pytest_compliance_rule_engine.models import (
    ComplianceRule,
    ComplianceRuleSet,
    ComplianceRuleSeverityChoices,
    ComplianceTestResult,
    ComplianceTestResultStatusChoices,
)

VALID_RULE_CODE = "def test_ntp(configuration):\n    assert 'ntp' in configuration"


class AppTest(APITestCase):
    """The app's API root is reachable."""

    def test_root(self):
        url = reverse("plugins-api:nautobot_pytest_compliance_rule_engine-api:api-root")
        response = self.client.get(f"{url}?format=api", **self.header)

        self.assertEqual(response.status_code, 200)


class ComplianceRuleTest(APIViewTestCases.APIViewTestCase):
    """CRUD and permission tests for the ComplianceRule API endpoint."""

    model = ComplianceRule
    choices_fields = {"severity"}
    create_data = [
        {"name": "API Rule 4", "rule_code": VALID_RULE_CODE},
        {"name": "API Rule 5", "rule_code": VALID_RULE_CODE, "severity": ComplianceRuleSeverityChoices.HIGH},
        {"name": "API Rule 6", "rule_code": VALID_RULE_CODE, "description": "Created via the API"},
    ]
    update_data = {
        "description": "Updated via the API",
        "rule_code": VALID_RULE_CODE,
    }
    bulk_update_data = {
        "severity": ComplianceRuleSeverityChoices.LOW,
    }

    @classmethod
    def setUpTestData(cls):
        ComplianceRule.objects.create(name="API Rule 1", rule_code=VALID_RULE_CODE)
        ComplianceRule.objects.create(name="API Rule 2", rule_code=VALID_RULE_CODE)
        ComplianceRule.objects.create(name="API Rule 3", rule_code=VALID_RULE_CODE)


class ComplianceRuleSetTest(APIViewTestCases.APIViewTestCase):
    """CRUD and permission tests for the ComplianceRuleSet API endpoint."""

    model = ComplianceRuleSet
    create_data = [
        {"name": "API Rule Set 4"},
        {"name": "API Rule Set 5", "description": "Created via the API"},
        {"name": "API Rule Set 6"},
    ]
    update_data = {
        "description": "Updated via the API",
    }
    bulk_update_data = {
        "description": "Bulk updated via the API",
    }

    @classmethod
    def setUpTestData(cls):
        rule = ComplianceRule.objects.create(name="API Rule Set Member", rule_code=VALID_RULE_CODE)

        rule_set_1 = ComplianceRuleSet.objects.create(name="API Rule Set 1")
        rule_set_1.rules.add(rule)
        ComplianceRuleSet.objects.create(name="API Rule Set 2")
        ComplianceRuleSet.objects.create(name="API Rule Set 3")


class ComplianceTestResultTest(
    APIViewTestCases.GetObjectViewTestCase,
    APIViewTestCases.ListObjectsViewTestCase,
):
    """List/detail-view and permission tests for the read-only ComplianceTestResult API endpoint.

    Only Get and List apply here -- there is no create/edit/delete API for
    ComplianceTestResult since results are system-generated by the RunComplianceRules Job.
    """

    model = ComplianceTestResult
    choices_fields = {"status"}

    @classmethod
    def setUpTestData(cls):
        device_ct = ContentType.objects.get_for_model(Device)
        location_ct = ContentType.objects.get_for_model(Location)

        manufacturer = Manufacturer.objects.create(name="API Result Manufacturer")
        device_type = DeviceType.objects.create(manufacturer=manufacturer, model="API Result Device Type")

        location_type = LocationType.objects.create(name="API Result Location Type")
        location_type.content_types.add(device_ct)

        location_status = Status.objects.create(name="API Result Location Status")
        location_status.content_types.add(location_ct)
        location = Location.objects.create(
            name="API Result Location",
            location_type=location_type,
            status=location_status,
        )

        device_role = Role.objects.create(name="API Result Device Role")
        device_role.content_types.add(device_ct)

        device_status = Status.objects.create(name="API Result Device Status")
        device_status.content_types.add(device_ct)

        device_1 = Device.objects.create(
            name="API Result Device 1",
            device_type=device_type,
            role=device_role,
            location=location,
            status=device_status,
        )
        device_2 = Device.objects.create(
            name="API Result Device 2",
            device_type=device_type,
            role=device_role,
            location=location,
            status=device_status,
        )

        low_rule = ComplianceRule.objects.create(
            name="API Result Low Severity Rule",
            severity=ComplianceRuleSeverityChoices.LOW,
            rule_code=VALID_RULE_CODE,
        )
        high_rule = ComplianceRule.objects.create(
            name="API Result High Severity Rule",
            severity=ComplianceRuleSeverityChoices.HIGH,
            rule_code=VALID_RULE_CODE,
        )

        ComplianceTestResult.objects.create(
            rule=low_rule,
            device=device_1,
            status=ComplianceTestResultStatusChoices.PASS,
        )
        ComplianceTestResult.objects.create(
            rule=low_rule,
            device=device_2,
            status=ComplianceTestResultStatusChoices.FAIL,
            output="AssertionError: 'ntp' not in configuration",
        )
        ComplianceTestResult.objects.create(
            rule=high_rule,
            device=device_1,
            status=ComplianceTestResultStatusChoices.ERROR,
            output="KeyError: 'configuration'",
        )
        ComplianceTestResult.objects.create(
            rule=high_rule,
            device=device_2,
            status=ComplianceTestResultStatusChoices.PASS,
        )

    def test_filter_by_status_narrows_results(self):
        """Filtering the list endpoint by status only returns results with that status."""
        self.add_permissions("nautobot_pytest_compliance_rule_engine.view_compliancetestresult")

        response = self.client.get(f"{self._get_list_url()}?status=fail", **self.header)

        self.assertHttpStatus(response, status.HTTP_200_OK)
        self.assertEqual(response.data["count"], 1)

    def test_filter_by_severity_narrows_results(self):
        """Filtering the list endpoint by the rule's severity only returns matching results."""
        self.add_permissions("nautobot_pytest_compliance_rule_engine.view_compliancetestresult")

        response = self.client.get(f"{self._get_list_url()}?severity=high", **self.header)

        self.assertHttpStatus(response, status.HTTP_200_OK)
        self.assertEqual(response.data["count"], 2)

    def test_filter_by_device_narrows_results(self):
        """Filtering the list endpoint by device only returns results for that device."""
        self.add_permissions("nautobot_pytest_compliance_rule_engine.view_compliancetestresult")

        device_1 = Device.objects.get(name="API Result Device 1")
        response = self.client.get(f"{self._get_list_url()}?device={device_1.pk}", **self.header)

        self.assertHttpStatus(response, status.HTTP_200_OK)
        self.assertEqual(response.data["count"], 2)

    def test_filter_by_run_datetime_range_narrows_results(self):
        """Filtering the list endpoint by a run_datetime range only returns results in range."""
        self.add_permissions("nautobot_pytest_compliance_rule_engine.view_compliancetestresult")

        response = self.client.get(f"{self._get_list_url()}?run_datetime__gte=2099-01-01", **self.header)

        self.assertHttpStatus(response, status.HTTP_200_OK)
        self.assertEqual(response.data["count"], 0)

    def test_create_not_allowed(self):
        """POSTing to the list endpoint is rejected -- results are system-generated only.

        Grants add/change/delete/view permission so the 405 reflects the endpoint's
        read-only wiring, not merely a 403 from a user who lacks write permission.
        """
        self.add_permissions(
            "nautobot_pytest_compliance_rule_engine.view_compliancetestresult",
            "nautobot_pytest_compliance_rule_engine.add_compliancetestresult",
        )

        response = self.client.post(self._get_list_url(), {}, format="json", **self.header)

        self.assertHttpStatus(response, status.HTTP_405_METHOD_NOT_ALLOWED)

    def test_update_not_allowed(self):
        """PUTting to a detail endpoint is rejected -- results are system-generated only.

        Grants change permission so the 405 reflects the endpoint's read-only wiring,
        not merely a 403 from a user who lacks write permission.
        """
        self.add_permissions(
            "nautobot_pytest_compliance_rule_engine.view_compliancetestresult",
            "nautobot_pytest_compliance_rule_engine.change_compliancetestresult",
        )

        instance = self._get_queryset().first()
        response = self.client.put(self._get_detail_url(instance), {}, format="json", **self.header)

        self.assertHttpStatus(response, status.HTTP_405_METHOD_NOT_ALLOWED)

    def test_delete_not_allowed(self):
        """DELETEing a detail endpoint is rejected -- results are system-generated only.

        Grants delete permission so the 405 reflects the endpoint's read-only wiring,
        not merely a 403 from a user who lacks write permission.
        """
        self.add_permissions(
            "nautobot_pytest_compliance_rule_engine.view_compliancetestresult",
            "nautobot_pytest_compliance_rule_engine.delete_compliancetestresult",
        )

        instance = self._get_queryset().first()
        response = self.client.delete(self._get_detail_url(instance), **self.header)

        self.assertHttpStatus(response, status.HTTP_405_METHOD_NOT_ALLOWED)
