"""UI view tests for ComplianceRule, ComplianceRuleSet, and ComplianceTestResult.

Uses Nautobot's `ViewTestCases`, which exercises get/create/edit/delete/list/bulk-delete
both with and without the relevant object permission -- so each test case below covers
a 200 for a superuser and a 403/404 for a permission-restricted user without hand-rolling
that matrix. Bulk-edit is intentionally not exercised here since no BulkEditForm is
defined for these models.
"""

from django.contrib.contenttypes.models import ContentType
from nautobot.core.testing import ViewTestCases, extract_page_body
from nautobot.dcim.models import Device, DeviceType, Location, LocationType, Manufacturer
from nautobot.extras.models import Role, Status

from nautobot_pytest_compliance_rule_engine.models import (
    ComplianceRule,
    ComplianceRuleSet,
    ComplianceRuleSeverityChoices,
    ComplianceTestResult,
    ComplianceTestResultStatusChoices,
)

VALID_RULE_CODE = "def test_ntp(configuration):\n    assert 'ntp' in configuration"


class ComplianceRuleViewTest(
    ViewTestCases.GetObjectViewTestCase,
    ViewTestCases.GetObjectChangelogViewTestCase,
    ViewTestCases.GetObjectNotesViewTestCase,
    ViewTestCases.CreateObjectViewTestCase,
    ViewTestCases.EditObjectViewTestCase,
    ViewTestCases.DeleteObjectViewTestCase,
    ViewTestCases.ListObjectsViewTestCase,
    ViewTestCases.BulkDeleteObjectsViewTestCase,
):
    """CRUD and permission tests for the ComplianceRule UI views."""

    model = ComplianceRule

    @classmethod
    def setUpTestData(cls):
        ComplianceRule.objects.create(name="View Rule 1", rule_code=VALID_RULE_CODE)
        ComplianceRule.objects.create(name="View Rule 2", rule_code=VALID_RULE_CODE)
        ComplianceRule.objects.create(name="View Rule 3", rule_code=VALID_RULE_CODE)
        ComplianceRule.objects.create(name="View Rule 4", rule_code=VALID_RULE_CODE)

        cls.form_data = {
            "name": "View Rule 5",
            "description": "Created via the UI",
            "severity": ComplianceRuleSeverityChoices.HIGH,
            "rule_code": VALID_RULE_CODE,
            "enabled": True,
            "tags": [],
        }


class ComplianceRuleSetViewTest(
    ViewTestCases.GetObjectViewTestCase,
    ViewTestCases.GetObjectChangelogViewTestCase,
    ViewTestCases.GetObjectNotesViewTestCase,
    ViewTestCases.CreateObjectViewTestCase,
    ViewTestCases.EditObjectViewTestCase,
    ViewTestCases.DeleteObjectViewTestCase,
    ViewTestCases.ListObjectsViewTestCase,
    ViewTestCases.BulkDeleteObjectsViewTestCase,
):
    """CRUD and permission tests for the ComplianceRuleSet UI views."""

    model = ComplianceRuleSet

    @classmethod
    def setUpTestData(cls):
        rule = ComplianceRule.objects.create(name="View Rule Set Member", rule_code=VALID_RULE_CODE)

        rule_set_1 = ComplianceRuleSet.objects.create(name="View Rule Set 1")
        rule_set_1.rules.add(rule)
        ComplianceRuleSet.objects.create(name="View Rule Set 2")
        ComplianceRuleSet.objects.create(name="View Rule Set 3")
        ComplianceRuleSet.objects.create(name="View Rule Set 4")

        cls.form_data = {
            "name": "View Rule Set 5",
            "description": "Created via the UI",
            "rules": [rule.pk],
            "tags": [],
        }


class ComplianceTestResultViewTest(
    ViewTestCases.GetObjectViewTestCase,
    ViewTestCases.ListObjectsViewTestCase,
):
    """List/detail-view and permission tests for the read-only ComplianceTestResult UI view.

    Only Get and List apply here -- there is no create/edit/delete UI for
    ComplianceTestResult since results are system-generated by the RunComplianceRules Job.
    """

    model = ComplianceTestResult

    @classmethod
    def setUpTestData(cls):
        device_ct = ContentType.objects.get_for_model(Device)
        location_ct = ContentType.objects.get_for_model(Location)

        manufacturer = Manufacturer.objects.create(name="View Result Manufacturer")
        device_type = DeviceType.objects.create(manufacturer=manufacturer, model="View Result Device Type")

        location_type = LocationType.objects.create(name="View Result Location Type")
        location_type.content_types.add(device_ct)

        location_status = Status.objects.create(name="View Result Location Status")
        location_status.content_types.add(location_ct)
        location = Location.objects.create(
            name="View Result Location",
            location_type=location_type,
            status=location_status,
        )

        device_role = Role.objects.create(name="View Result Device Role")
        device_role.content_types.add(device_ct)

        device_status = Status.objects.create(name="View Result Device Status")
        device_status.content_types.add(device_ct)

        cls.device_1 = Device.objects.create(
            name="View Result Device 1",
            device_type=device_type,
            role=device_role,
            location=location,
            status=device_status,
        )
        cls.device_2 = Device.objects.create(
            name="View Result Device 2",
            device_type=device_type,
            role=device_role,
            location=location,
            status=device_status,
        )

        cls.low_rule = ComplianceRule.objects.create(
            name="View Result Low Severity Rule",
            severity=ComplianceRuleSeverityChoices.LOW,
            rule_code=VALID_RULE_CODE,
        )
        cls.high_rule = ComplianceRule.objects.create(
            name="View Result High Severity Rule",
            severity=ComplianceRuleSeverityChoices.HIGH,
            rule_code=VALID_RULE_CODE,
        )

        ComplianceTestResult.objects.create(
            rule=cls.low_rule,
            device=cls.device_1,
            status=ComplianceTestResultStatusChoices.PASS,
        )
        ComplianceTestResult.objects.create(
            rule=cls.low_rule,
            device=cls.device_2,
            status=ComplianceTestResultStatusChoices.FAIL,
            output="AssertionError: 'ntp' not in configuration",
        )
        ComplianceTestResult.objects.create(
            rule=cls.high_rule,
            device=cls.device_1,
            status=ComplianceTestResultStatusChoices.ERROR,
            output="KeyError: 'configuration'",
        )
        ComplianceTestResult.objects.create(
            rule=cls.high_rule,
            device=cls.device_2,
            status=ComplianceTestResultStatusChoices.PASS,
        )

    def test_filter_by_status_narrows_results(self):
        """Filtering the list view by status only returns results with that status."""
        self.add_permissions("nautobot_pytest_compliance_rule_engine.view_compliancetestresult")

        response = self.client.get(f"{self._get_url('list')}?status=fail")

        self.assertHttpStatus(response, 200)
        content = extract_page_body(response.content.decode(response.charset))
        self.assertIn("View Result Device 2", content)
        self.assertNotIn("View Result High Severity Rule", content)

    def test_filter_by_severity_narrows_results(self):
        """Filtering the list view by the rule's severity only returns matching results."""
        self.add_permissions("nautobot_pytest_compliance_rule_engine.view_compliancetestresult")

        response = self.client.get(f"{self._get_url('list')}?severity=high")

        self.assertHttpStatus(response, 200)
        content = extract_page_body(response.content.decode(response.charset))
        self.assertIn("View Result High Severity Rule", content)
        self.assertNotIn("View Result Low Severity Rule", content)

    def test_filter_by_device_narrows_results(self):
        """Filtering the list view by device only returns results for that device."""
        self.add_permissions("nautobot_pytest_compliance_rule_engine.view_compliancetestresult")

        response = self.client.get(f"{self._get_url('list')}?device={self.device_1.pk}")

        self.assertHttpStatus(response, 200)
        content = extract_page_body(response.content.decode(response.charset))
        self.assertIn("View Result Low Severity Rule", content)
        self.assertNotIn("View Result Device 2", content)
