"""Views for nautobot_pytest_compliance_rule_engine."""

from nautobot.apps.views import NautobotUIViewSet, ObjectDetailViewMixin, ObjectListViewMixin, ObjectView
from nautobot.dcim.models import Device

from nautobot_pytest_compliance_rule_engine import forms, tables
from nautobot_pytest_compliance_rule_engine.api.serializers import ComplianceRuleSerializer, ComplianceRuleSetSerializer
from nautobot_pytest_compliance_rule_engine.filters import (
    ComplianceRuleFilterSet,
    ComplianceRuleSetFilterSet,
    ComplianceTestResultFilterSet,
)
from nautobot_pytest_compliance_rule_engine.models import ComplianceRule, ComplianceRuleSet, ComplianceTestResult

# How many of the device's most recent ComplianceTestResult rows to show in the Compliance tab.
DEVICE_COMPLIANCE_TAB_RESULTS_LIMIT = 20


class ComplianceRuleUIViewSet(NautobotUIViewSet):
    """List/detail/edit/delete views for ComplianceRule."""

    queryset = ComplianceRule.objects.all()
    filterset_class = ComplianceRuleFilterSet
    filterset_form_class = forms.ComplianceRuleFilterForm
    form_class = forms.ComplianceRuleForm
    serializer_class = ComplianceRuleSerializer
    table_class = tables.ComplianceRuleTable


class ComplianceRuleSetUIViewSet(NautobotUIViewSet):
    """List/detail/edit/delete views for ComplianceRuleSet."""

    queryset = ComplianceRuleSet.objects.all()
    filterset_class = ComplianceRuleSetFilterSet
    filterset_form_class = forms.ComplianceRuleSetFilterForm
    form_class = forms.ComplianceRuleSetForm
    serializer_class = ComplianceRuleSetSerializer
    table_class = tables.ComplianceRuleSetTable


class ComplianceTestResultUIViewSet(ObjectDetailViewMixin, ObjectListViewMixin):
    """Read-only list/detail views for ComplianceTestResult.

    Results are system-generated by the RunComplianceRules Job (M3), so only list and
    retrieve are wired up here -- omitting the edit/destroy/bulk mixins that
    NautobotUIViewSet includes keeps there being no add/edit/delete UI, while still
    giving each result a `get_absolute_url()` so table rows and links resolve.
    """

    queryset = ComplianceTestResult.objects.select_related("rule", "device")
    filterset_class = ComplianceTestResultFilterSet
    filterset_form_class = forms.ComplianceTestResultFilterForm
    table_class = tables.ComplianceTestResultTable
    action_buttons = ("export",)


class DeviceComplianceTabView(ObjectView):
    """Render the device's most recent ComplianceTestResult rows as a "Compliance" tab.

    Nautobot 2.4.5's `dcim/device.html` fully overrides `generic/object_retrieve.html`'s `content`
    block without including `{% plugin_object_detail_tab_content %}`, so a `Tab` registered via
    `TemplateExtension.object_detail_tabs` never gets its panels rendered on the Device detail page.
    `template_content.py` instead registers a `DistinctViewTab` that links here; this view's
    template extends `dcim/device/base.html` directly, bypassing that override.
    """

    queryset = Device.objects.all()
    template_name = "nautobot_pytest_compliance_rule_engine/device_compliance_tab.html"

    def get_extra_context(self, request, instance):
        """Add the device's most recent ComplianceTestResult rows, as a table, to the context."""
        results = (
            ComplianceTestResult.objects.restrict(request.user, "view")
            .filter(device=instance)
            .select_related("rule")
            .order_by("-run_datetime")[:DEVICE_COMPLIANCE_TAB_RESULTS_LIMIT]
        )
        return {
            **super().get_extra_context(request, instance),
            "compliance_results_table": tables.ComplianceTestResultTable(results, exclude=("device",)),
        }
