"""Views for nautobot_pytest_compliance_rule_engine."""

from nautobot.apps.views import NautobotUIViewSet, ObjectDetailViewMixin, ObjectListViewMixin

from nautobot_pytest_compliance_rule_engine import forms, tables
from nautobot_pytest_compliance_rule_engine.api.serializers import ComplianceRuleSerializer, ComplianceRuleSetSerializer
from nautobot_pytest_compliance_rule_engine.filters import (
    ComplianceRuleFilterSet,
    ComplianceRuleSetFilterSet,
    ComplianceTestResultFilterSet,
)
from nautobot_pytest_compliance_rule_engine.models import ComplianceRule, ComplianceRuleSet, ComplianceTestResult


class ComplianceRuleUIViewSet(NautobotUIViewSet):
    """List/detail/edit/delete views for ComplianceRule."""

    queryset = ComplianceRule.objects.all()
    filterset_class = ComplianceRuleFilterSet
    filterset_form_class = forms.ComplianceRuleFilterForm
    form_class = forms.ComplianceRuleForm
    serializer_class = ComplianceRuleSerializer
    table_class = tables.ComplianceRuleTable


class ComplianceRuleSetUIViewSet(NautobotUIViewSet):
    """List/detail/edit/delete views for ComplianceRuleSet."""

    queryset = ComplianceRuleSet.objects.all()
    filterset_class = ComplianceRuleSetFilterSet
    filterset_form_class = forms.ComplianceRuleSetFilterForm
    form_class = forms.ComplianceRuleSetForm
    serializer_class = ComplianceRuleSetSerializer
    table_class = tables.ComplianceRuleSetTable


class ComplianceTestResultUIViewSet(ObjectDetailViewMixin, ObjectListViewMixin):
    """Read-only list/detail views for ComplianceTestResult.

    Results are system-generated by the RunComplianceRules Job (M3), so only list and
    retrieve are wired up here -- omitting the edit/destroy/bulk mixins that
    NautobotUIViewSet includes keeps there being no add/edit/delete UI, while still
    giving each result a `get_absolute_url()` so table rows and links resolve.
    """

    queryset = ComplianceTestResult.objects.select_related("rule", "device")
    filterset_class = ComplianceTestResultFilterSet
    filterset_form_class = forms.ComplianceTestResultFilterForm
    table_class = tables.ComplianceTestResultTable
    action_buttons = ("export",)
